sudo: false
language: node_js
node_js:
  - "11.10.1"
env:
  - CI=true

cache:
  yarn: true
  directories:
    - node_modules # NPM packages

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  - export PATH=$HOME/.yarn/bin:$PATH
  - cd ToDo/React/wickedev_project

# command to install dependencies
install:
  - yarn

# command to run tests
script:
  - yarn test
  - yarn lint
  - yarn build
